### ISSUE TITLE
[Discussion/Question]: what to do when a version doesn't exist on CRAN nor on GitHub tag?

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/verdepcheck#37]
### What is your question?

On `strategy: release` Should we default to GitHub if version doesn't exist on CRAN / GH tag?

### Example

Context, `teal.slice` last release/tag is `0.4.0`. The development `main` branch is at `0.4.9013`

`teal`'s development dependency `teal.slice` version was changed:

- From `teal.slice (>= 0.4.0)`
- To `teal.slice (>= 0.4.9011)`
  - due to a new function only available from that _(dev)_ version

### Current outcome:

- ❌ `verdepcheck` fails to find version `0.4.9011` as it's not released on CRAN tagged on GitHub

### Possible solution:

1. Accept this limitation
2. When version is not found on CRAN, nor on GitHub tags, it uses the latest development version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

**Comment by averissimo** [comment]
_(moving discussion from chat to issue @pawelru)_

**Comment by pawelru** [comment]
For me this is an obvious expected failure (true negative) - testing against released version of dependency fails because development version is required.
This gives an important information to a `teal` maintainer that it cannot be released before releasing `teal.slice` first.
From a different angle: if you decide to vbump any dependency to a devel version it is expected that the release strategy will fail. 

> When version is not found on CRAN, nor on GitHub tags, it uses the latest development version

If you do this then you are somewhat mixing `max` and `release` strategy. In the example you provided: `teal` maintainer won't be notified that `teal` cannot be released before releasing `teal.slice` first.

It's quite clear for me. Please let me know if you need some further explanation. If not - let's close this.
